# Generated by a toy compiler from /workspaces/risc-v_cpu/toy_compile/src/main.lang
# Target: RISC-V (RV32I)

.text
.global _start
_start:
    call main
    li a7, 93
    ecall
multiply:
    addi sp, sp, -48
    sw ra, 36(sp)
    sw s1, 40(sp)
    sw s0, 44(sp)
    addi s0, sp, 48
    sw a0, -16(s0)
    sw a1, -20(s0)
    li t0, 0
    sw t0, -24(s0)
    lw t0, -20(s0)
    li t1, 0
    xor t0, t0, t1
    seqz t0, t0
    blez t0, else_1
    li t0, 0
    sw t0, -24(s0)
    j if_end_0
else_1:
    sw t0, -28(s0)
    sw t2, -32(s0)
    sw a0, -36(s0)
    sw a1, -40(s0)
    lw a0, -16(s0)
    lw t1, -20(s0)
    li t2, 1
    sub t1, t1, t2
    mv a1, t1
    call multiply
    mv s1, a0
    lw t0, -28(s0)
    lw t2, -32(s0)
    lw a0, -36(s0)
    lw a1, -40(s0)
    mv t1, s1
    lw t2, -16(s0)
    add t1, t1, t2
    mv t0, t1
    sw t0, -24(s0)
if_end_0:
    lw a0, -24(s0)
    lw ra, -12(s0)
    lw s1, -8(s0)
    lw s0, -4(s0)
    addi sp, sp, 48
    ret
main:
    addi sp, sp, -32
    sw ra, 20(sp)
    sw s1, 24(sp)
    sw s0, 28(sp)
    addi s0, sp, 32
    sw t0, -16(s0)
    sw t1, -20(s0)
    sw t2, -24(s0)
    sw a0, -28(s0)
    sw a1, -32(s0)
    li a0, 12
    li a1, 11
    call multiply
    mv s1, a0
    lw t0, -16(s0)
    lw t1, -20(s0)
    lw t2, -24(s0)
    lw a0, -28(s0)
    lw a1, -32(s0)
    mv a0, s1
    lw ra, -12(s0)
    lw s1, -8(s0)
    lw s0, -4(s0)
    addi sp, sp, 32
    ret
